//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp3TagReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp3TagReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string APIC_00 {
            get {
                return ResourceManager.GetString("APIC:00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32x32 pixels &apos;file icon&apos; (PNG only).
        /// </summary>
        internal static string APIC_01 {
            get {
                return ResourceManager.GetString("APIC:01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other file icon.
        /// </summary>
        internal static string APIC_02 {
            get {
                return ResourceManager.GetString("APIC:02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover (front).
        /// </summary>
        internal static string APIC_03 {
            get {
                return ResourceManager.GetString("APIC:03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover (back).
        /// </summary>
        internal static string APIC_04 {
            get {
                return ResourceManager.GetString("APIC:04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaflet page.
        /// </summary>
        internal static string APIC_05 {
            get {
                return ResourceManager.GetString("APIC:05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media (e.g. lable side of CD).
        /// </summary>
        internal static string APIC_06 {
            get {
                return ResourceManager.GetString("APIC:06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead artist/lead performer/soloist.
        /// </summary>
        internal static string APIC_07 {
            get {
                return ResourceManager.GetString("APIC:07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist/performer.
        /// </summary>
        internal static string APIC_08 {
            get {
                return ResourceManager.GetString("APIC:08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor.
        /// </summary>
        internal static string APIC_09 {
            get {
                return ResourceManager.GetString("APIC:09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band/Orchestra.
        /// </summary>
        internal static string APIC_0A {
            get {
                return ResourceManager.GetString("APIC:0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        internal static string APIC_0B {
            get {
                return ResourceManager.GetString("APIC:0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyricist/text writer.
        /// </summary>
        internal static string APIC_0C {
            get {
                return ResourceManager.GetString("APIC:0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Location.
        /// </summary>
        internal static string APIC_0D {
            get {
                return ResourceManager.GetString("APIC:0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During recording.
        /// </summary>
        internal static string APIC_0E {
            get {
                return ResourceManager.GetString("APIC:0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During performance.
        /// </summary>
        internal static string APIC_0F {
            get {
                return ResourceManager.GetString("APIC:0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie/video screen capture.
        /// </summary>
        internal static string APIC_10 {
            get {
                return ResourceManager.GetString("APIC:10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bright coloured fish.
        /// </summary>
        internal static string APIC_11 {
            get {
                return ResourceManager.GetString("APIC:11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustration.
        /// </summary>
        internal static string APIC_12 {
            get {
                return ResourceManager.GetString("APIC:12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band/artist logotype.
        /// </summary>
        internal static string APIC_13 {
            get {
                return ResourceManager.GetString("APIC:13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher/Studio logotype.
        /// </summary>
        internal static string APIC_14 {
            get {
                return ResourceManager.GetString("APIC:14", resourceCulture);
            }
        }
    }
}
